### ISSUE TITLE
./install.sh not running

### ISSUE THREAD

**Issue by SyCode7** [jarvis-mark42/openstack#1]

**Comment by harshitanand** [comment]
Give a brief about error

**Comment by SyCode7** [comment]
Hi, i wanted a juno installation so i cloned your repo. Upon successful cloning, I set
some basic environment variables in the local.conf and then ran ./stack.sh.....there was no response.
Tried to make it executable but this didnt help.
Thanks !

**Comment by harshitanand** [comment]
Please follow readme correctly you need not do any thing just clone the repo and goto environments/variables.sh set passwords and save file. Please check permissions of files before executing
